const CLOUDINARY_HOST = "joi-de-vivro"
const CLOUDINARY_API_KEY = "615461439126173"
const CLOUDINARY_API_SECRET = "vVK2PxzDr8RQWmTwbCCO6Sd7UEQ"

const cloudina ={
    CLOUDINARY_HOST,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET
}

export default cloudina;